"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarDays, Download, LoaderCircle, Printer, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { formatCurrency } from "@/lib/utils";

type Definition = { id: string; type: string; code: string; name: string; parentId: string | null };
type Stat = { typeId: string; type: string; count: number; sentCount: number; incoming: number; service: number; fund: number; pending: number; records: number };
type Detail = { id: string; typeId: string; receiptNo: string; donorName: string; phone: string; origin: string; destination: string; payment: string; quantity: number; amount: number; sent: boolean; date: string };
type Filters = { year: string; month: string; from: string; to: string; typeId: string; originCountry: string; originCity: string; paymentMethodId: string; destinationCountryId: string; destinationRegionId: string; partnerId: string; range: string };
const initial: Filters = { year: "2026", month: "", from: "", to: "", typeId: "", originCountry: "", originCity: "", paymentMethodId: "", destinationCountryId: "", destinationRegionId: "", partnerId: "", range: "" };
const control = "h-9 w-full rounded-md border border-slate-200 bg-white px-3 text-xs text-slate-700 outline-none focus:border-cyan-500";

function escapeHtml(value: string | number) {
  return String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ?? character);
}

export function GeneralDonationStatisticsReport() {
  const [filters, setFilters] = useState(initial); const [rows, setRows] = useState<Stat[]>([]); const [details, setDetails] = useState<Detail[]>([]); const [definitions, setDefinitions] = useState<Definition[]>([]); const [originCountries, setOriginCountries] = useState<string[]>([]); const [originCities, setOriginCities] = useState<string[]>([]); const [selected, setSelected] = useState<Stat | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async (active: Filters) => { setLoading(true); setError(""); const query = new URLSearchParams(); Object.entries(active).forEach(([key,value])=>{if(value)query.set(key,value)}); try { const response=await fetch(`/api/reports/general-donation-statistics?${query}`,{cache:"no-store"}); const data=await response.json() as {rows?:Stat[];details?:Detail[];filters?:{definitions:Definition[];originCountries:string[];originCities:string[]};message?:string}; if(!response.ok)throw new Error(data.message); setRows(data.rows??[]);setDetails(data.details??[]);setDefinitions(data.filters?.definitions??[]);setOriginCountries(data.filters?.originCountries??[]);setOriginCities(data.filters?.originCities??[]); } catch(reason){setError(reason instanceof Error?reason.message:"Rapor yüklenemedi.")} finally{setLoading(false)} },[]);
  useEffect(()=>{void load(initial)},[load]);
  const types=definitions.filter((d)=>d.type==="DONATION_TYPE"), payments=definitions.filter((d)=>d.type==="PAYMENT_METHOD"), countries=definitions.filter((d)=>d.type==="DESTINATION_COUNTRY"), regions=definitions.filter((d)=>d.type==="DESTINATION_REGION"&&(!filters.destinationCountryId||d.parentId===filters.destinationCountryId)), partners=definitions.filter((d)=>d.type==="PARTNER"&&(!filters.destinationCountryId||d.parentId===filters.destinationCountryId));
  const totals=useMemo(()=>rows.reduce((sum,row)=>({count:sum.count+row.count,sentCount:sum.sentCount+row.sentCount,incoming:sum.incoming+row.incoming,service:sum.service+row.service,fund:sum.fund+row.fund,pending:sum.pending+row.pending}),{count:0,sentCount:0,incoming:0,service:0,fund:0,pending:0}),[rows]);
  function update(field:keyof Filters,value:string){setFilters((current)=>field==="originCountry"?{...current,originCountry:value,originCity:"",range:""}:field==="destinationCountryId"?{...current,destinationCountryId:value,destinationRegionId:"",partnerId:"",range:""}:{...current,[field]:value,range:field==="range"?value:""})}
  function quickRange(range:string){const next={...filters,range,year:"",month:"",from:"",to:""};setFilters(next);void load(next)}
  function exportCsv(){const data=[["Bağış Cinsi","Toplam Adet","Gelen Toplam","Hizmet/Gönderilen","Toplam Fon","Ödeme Bekleyen"],...rows.map((r)=>[r.type,String(r.count),String(r.incoming),String(r.service),String(r.fund),String(r.pending)]),["GENEL TOPLAM",String(totals.count),String(totals.incoming),String(totals.service),String(totals.fund),String(totals.pending)]];const csv=`\uFEFF${data.map((r)=>r.map((c)=>`"${c.replaceAll('"','""')}"`).join(";")).join("\n")}`;const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="genel-bagis-istatistik.csv";a.click();URL.revokeObjectURL(url)}
  function printReport(){
    const popup=window.open("",`general-statistics-${Date.now()}`,"width=1200,height=850");if(!popup)return;
    const filterSummary=[filters.range==="today"?"Bugün":filters.range==="month"?"Bu Ay":filters.range==="year"?"Bu Yıl":"",filters.year?`${filters.year}${filters.month?` / ${filters.month}. ay`:""}`:"",filters.from||filters.to?`${filters.from||"Başlangıç"} – ${filters.to||"Bugün"}`:"",types.find((i)=>i.id===filters.typeId)?.name,filters.originCountry,filters.originCity,payments.find((i)=>i.id===filters.paymentMethodId)?.name,countries.find((i)=>i.id===filters.destinationCountryId)?.name,regions.find((i)=>i.id===filters.destinationRegionId)?.name].filter(Boolean).join(" · ")||"Tüm genel bağış kayıtları";
    const tableRows=rows.map((row)=>`<tr><td><strong>${escapeHtml(row.type)}</strong><small>${row.records} kayıt</small></td><td>${row.count.toLocaleString("tr-TR")}</td><td>${escapeHtml(formatCurrency(row.incoming))}</td><td>${escapeHtml(formatCurrency(row.service))}</td><td class="fund">${escapeHtml(formatCurrency(row.fund))}</td><td>${escapeHtml(formatCurrency(row.pending))}</td></tr>`).join("");
    popup.document.write(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>Genel Bağış İstatistik Raporu</title><style>
@page{size:A4 landscape;margin:10mm}*{box-sizing:border-box}body{margin:0;color:#153344;font-family:Arial,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}.sheet{width:100%;min-height:185mm}.brand{display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid #02b3aa;padding-bottom:10px}.brand-left{display:flex;align-items:center;gap:10px}.logo{width:38px;height:38px;object-fit:contain}.brand h1{margin:0;font-size:20px}.brand p,.meta{margin:3px 0 0;color:#718096;font-size:9px}.doc{text-align:right}.doc strong{display:block;font-size:12px;color:#02b3aa}.hero{display:flex;justify-content:space-between;align-items:center;margin:13px 0;padding:12px 15px;border-radius:10px;background:linear-gradient(120deg,#eefbf7,#edf8fc)}.hero h2{margin:0;font-size:17px}.hero p{margin:4px 0 0;font-size:9px;color:#64748b}.badge{padding:7px 12px;border-radius:20px;background:#02b3aa;color:white;font-size:10px;font-weight:700}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin-bottom:11px}.metric{padding:9px;border:1px solid #dbe7e4;border-radius:8px;background:#fff}.metric small{display:block;color:#718096;font-size:7px;text-transform:uppercase}.metric strong{display:block;margin-top:4px;font-size:12px}table{width:100%;border-collapse:collapse;font-size:8px}thead{background:#02b3aa;color:white}th,td{padding:7px;border:1px solid #dce6e4;text-align:right}th:first-child,td:first-child{text-align:left}tbody tr:nth-child(even){background:#f5faf9}td small{display:block;margin-top:2px;color:#8a9aa3;font-size:6.5px}.fund{color:#d52b2b;font-weight:800}tfoot{background:#376bc1;color:white;font-weight:800}.footer{display:flex;justify-content:space-between;margin-top:10px;padding-top:7px;border-top:1px solid #cfdad7;color:#718096;font-size:7px}@media print{html,body{width:297mm;min-height:210mm}.sheet{break-inside:avoid}}
</style></head><body><main class="sheet"><header class="brand"><div class="brand-left"><img class="logo" src="/yedirenk-logo.png" alt="Yedirenk Derneği"><div><h1>Yedirenk</h1><p>BAĞIŞ YÖNETİMİ</p></div></div><div class="doc"><strong>GENEL BAĞIŞ İSTATİSTİK RAPORU</strong><span class="meta">${escapeHtml(new Date().toLocaleString("tr-TR"))}</span></div></header><section class="hero"><div><h2>Genel Bağış Finansal Özeti</h2><p>${escapeHtml(filterSummary)}</p></div><div class="badge">${rows.length} bağış türü · ${totals.count} birim</div></section><section class="metrics"><div class="metric"><small>TOPLAM ADET</small><strong>${totals.count}</strong></div><div class="metric"><small>GELEN TOPLAM</small><strong>${escapeHtml(formatCurrency(totals.incoming))}</strong></div><div class="metric"><small>HİZMET / GÖNDERİLEN</small><strong>${escapeHtml(formatCurrency(totals.service))}</strong></div><div class="metric"><small>KALAN FON</small><strong>${escapeHtml(formatCurrency(totals.fund))}</strong></div><div class="metric"><small>ÖDEME BEKLEYEN</small><strong>${escapeHtml(formatCurrency(totals.pending))}</strong></div></section><table><thead><tr><th>BAĞIŞ CİNSİ</th><th>TOPLAM ADET</th><th>GELEN TOPLAM</th><th>HİZMET / GÖNDERİLEN</th><th>TOPLAM FON</th><th>ÖDEME BEKLEYEN</th></tr></thead><tbody>${tableRows||`<tr><td colspan="6" style="text-align:center;padding:30px">Seçili filtrelerde kayıt bulunamadı.</td></tr>`}</tbody><tfoot><tr><td>GENEL TOPLAM</td><td>${totals.count}</td><td>${escapeHtml(formatCurrency(totals.incoming))}</td><td>${escapeHtml(formatCurrency(totals.service))}</td><td>${escapeHtml(formatCurrency(totals.fund))}</td><td>${escapeHtml(formatCurrency(totals.pending))}</td></tr></tfoot></table><footer class="footer"><span>Yedirenk Derneği Bağış Yönetimi · Kurumsal Finansal Rapor</span><span>Gelen = Gönderilen + Kalan Fon + Ödeme Bekleyen</span></footer></main><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),250));<\/script></body></html>`);popup.document.close();
  }
  return <div id="printable-report" className="mx-auto max-w-[1540px]"><div className="print-hidden mb-4 flex items-end justify-between gap-3"><div><h2 className="text-xl font-bold text-[#0b2b3c]">Genel Bağış İstatistik</h2><p className="mt-1 text-xs text-slate-500">Tahsilat, gönderim, kalan fon ve bekleyen ödeme analizi</p></div><Button onClick={printReport}><Printer className="size-4"/> A4 Yazdır / PDF</Button></div><div className="hidden border-b-2 pb-3 print:block"><h1 className="text-xl font-bold">Yedirenk Derneği Bağış Yönetimi</h1><p className="text-xs">Genel Bağış İstatistik Raporu · {new Date().toLocaleString("tr-TR")}</p></div>
    <Card className="overflow-hidden"><div className="print-hidden border-b px-5 py-3 font-bold">Sorgulama</div><div className="grid gap-4 p-4 xl:grid-cols-[320px_1fr]">
      <aside className="print-hidden rounded-lg bg-[#2ba8c4] p-4"><Field label="Bölüm"><select className={control} disabled><option>Genel Bağış</option></select></Field><div className="grid grid-cols-2 gap-2"><Field label="Yıl"><select className={`${control} bg-yellow-200`} value={filters.year} onChange={(e)=>update("year",e.target.value)}><option value="">Seçiniz</option>{[2024,2025,2026].map(y=><option key={y}>{y}</option>)}</select></Field><Field label="Ay"><select className={control} value={filters.month} onChange={(e)=>update("month",e.target.value)}><option value="">Seçiniz</option>{["Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık"].map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></Field><Field label="İlk Tarih"><input className={control} type="date" value={filters.from} onChange={(e)=>update("from",e.target.value)}/></Field><Field label="Son Tarih"><input className={control} type="date" min={filters.from} value={filters.to} onChange={(e)=>update("to",e.target.value)}/></Field></div><Select label="Cinsi (Bağış Türü)" value={filters.typeId} items={types} onChange={(v)=>update("typeId",v)}/><StringSelect label="Bağış Gelen Ülke" value={filters.originCountry} items={originCountries} onChange={(v)=>update("originCountry",v)}/><StringSelect label="Bağış Gelen İl" value={filters.originCity} items={originCities} onChange={(v)=>update("originCity",v)}/><Select label="Ödeme Şekli" value={filters.paymentMethodId} items={payments} onChange={(v)=>update("paymentMethodId",v)}/><Select label="Bağış Giden Ülke" value={filters.destinationCountryId} items={countries} onChange={(v)=>update("destinationCountryId",v)}/><Select label="Giden Bölge" value={filters.destinationRegionId} items={regions} onChange={(v)=>update("destinationRegionId",v)}/><Select label="Ödeme Yapılan Partner/Firma" value={filters.partnerId} items={partners} onChange={(v)=>update("partnerId",v)}/><Button className="mt-3 w-full bg-violet-600 hover:bg-violet-700" onClick={()=>void load(filters)}><Search className="size-4"/> Sorgula</Button></aside>
      <section><div className="print-hidden mb-4 grid gap-3 sm:grid-cols-4"><Button variant="success" onClick={()=>quickRange("today")}><CalendarDays className="size-4"/> Bugün</Button><Button className="bg-red-500 hover:bg-red-600" onClick={()=>quickRange("month")}><CalendarDays className="size-4"/> Bu Ay</Button><Button variant="success" onClick={()=>quickRange("year")}><CalendarDays className="size-4"/> Bu Yıl</Button><Button variant="success" onClick={exportCsv}><Download className="size-4"/> Excel</Button></div><div className="overflow-hidden rounded-lg border"><h3 className="bg-[#2ba8c4] py-4 text-center text-xs font-bold uppercase text-white">Gelen Bağış Genel İstatistik Tablosu</h3><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-[11px]"><thead className="bg-[#02b3aa] text-white"><tr><th className="print-hidden p-3">Detay</th><th className="p-3">Bağış Cinsi</th><th className="p-3 text-right">Toplam Adet</th><th className="p-3 text-right">Gelen Toplam</th><th className="p-3 text-right">Hizmet/Gönderilen</th><th className="p-3 text-right">Toplam Fon</th><th className="p-3 text-right">Ödeme Bekleyen</th></tr></thead><tbody className="bg-yellow-50">{loading?<tr><td colSpan={7} className="p-16 text-center"><LoaderCircle className="mx-auto size-5 animate-spin"/></td></tr>:rows.map((row)=><tr key={row.typeId} className="border-b"><td className="print-hidden p-2"><button onClick={()=>setSelected(row)} className="rounded bg-[#029d95] px-3 py-2 font-semibold text-white">Detay Göster</button></td><td className="p-3 font-semibold">{row.type}<span className="block text-[9px] font-normal text-slate-400">{row.records} kayıt</span></td><td className="p-3 text-right">{row.count}</td><td className="p-3 text-right">{formatCurrency(row.incoming)}</td><td className="p-3 text-right">{formatCurrency(row.service)}</td><td className="p-3 text-right font-bold text-red-600">{formatCurrency(row.fund)}</td><td className="p-3 text-right">{formatCurrency(row.pending)}</td></tr>)}{!loading&&!rows.length?<tr><td colSpan={7} className="p-16 text-center">Kayıt bulunamadı.</td></tr>:null}</tbody><tfoot className="bg-[#376bc1] font-bold text-white"><tr><td className="print-hidden p-3"/><td className="p-3">GENEL TOPLAM</td><td className="p-3 text-right">{totals.count}</td><td className="p-3 text-right">{formatCurrency(totals.incoming)}</td><td className="p-3 text-right">{formatCurrency(totals.service)}</td><td className="p-3 text-right">{formatCurrency(totals.fund)}</td><td className="p-3 text-right">{formatCurrency(totals.pending)}</td></tr></tfoot></table></div></div>{error&&<p className="mt-3 rounded bg-red-50 p-3 text-xs text-red-700">{error}</p>}</section>
    </div></Card>{selected&&<DetailModal stat={selected} rows={details.filter((d)=>d.typeId===selected.typeId)} close={()=>setSelected(null)}/>}</div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-2 block text-[10px] font-bold text-white">{label}{children}</label>}
function Select({label,value,items,onChange}:{label:string;value:string;items:Definition[];onChange:(v:string)=>void}){return <Field label={label}><select className={control} value={value} onChange={(e)=>onChange(e.target.value)}><option value="">Seçiniz</option>{items.map((i)=><option key={i.id} value={i.id}>{i.name}</option>)}</select></Field>}
function StringSelect({label,value,items,onChange}:{label:string;value:string;items:string[];onChange:(v:string)=>void}){return <Field label={label}><select className={control} value={value} onChange={(e)=>onChange(e.target.value)}><option value="">Seçiniz</option>{items.map((i)=><option key={i}>{i}</option>)}</select></Field>}
function SentStatisticsTable({rows,loading,onDetail}:{rows:Stat[];loading:boolean;onDetail:(row:Stat)=>void}){const sent=rows.filter((row)=>row.sentCount>0||row.service>0);const count=sent.reduce((sum,row)=>sum+row.sentCount,0);const amount=sent.reduce((sum,row)=>sum+row.service,0);return <Card className="mt-5 overflow-hidden"><h3 className="bg-orange-500 py-4 text-center text-xs font-bold uppercase text-white">Gönderilen Genel İstatistik Tablosu</h3><table className="w-full text-left text-xs"><thead className="bg-[#02b3aa] text-white"><tr><th className="print-hidden p-3">Detay</th><th className="p-3">Ödenen Kasa / Bağış Türü</th><th className="p-3 text-right">Gönderilen Adet</th><th className="p-3 text-right">Gönderilen Toplam</th></tr></thead><tbody className="bg-yellow-50">{loading?<tr><td colSpan={4} className="p-12 text-center"><LoaderCircle className="mx-auto size-5 animate-spin"/></td></tr>:sent.map((row)=><tr key={row.typeId} className="border-b"><td className="print-hidden p-2"><button onClick={()=>onDetail(row)} className="rounded bg-[#029d95] px-3 py-2 font-semibold text-white">Detay Göster</button></td><td className="p-3 font-semibold">{row.type}</td><td className="p-3 text-right">{row.sentCount}</td><td className="p-3 text-right font-bold">{formatCurrency(row.service)}</td></tr>)}{!loading&&!sent.length?<tr><td colSpan={4} className="p-12 text-center text-slate-500">Gönderilmiş bağış kaydı bulunamadı.</td></tr>:null}</tbody><tfoot className="bg-[#376bc1] font-bold text-white"><tr><td className="print-hidden p-3"/><td className="p-3">GENEL TOPLAM</td><td className="p-3 text-right">{count}</td><td className="p-3 text-right">{formatCurrency(amount)}</td></tr></tfoot></table><p className="p-3 text-[10px] text-slate-500">* Yalnızca gönderim durumu işaretli genel bağış kayıtları hesaplanır.</p></Card>}
function DetailModal({stat,rows,close}:{stat:Stat;rows:Detail[];close:()=>void}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/45 p-4" onMouseDown={(e)=>{if(e.target===e.currentTarget)close()}}><div className="max-h-[85vh] w-full max-w-5xl overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-4"><div><h3 className="font-bold">{stat.type} Detayı</h3><p className="text-xs text-slate-500">{rows.length} kayıt · {formatCurrency(stat.incoming)}</p></div><button onClick={close}><X className="size-5"/></button></div><div className="max-h-[70vh] overflow-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="sticky top-0 bg-slate-100"><tr><th className="p-3">Makbuz</th><th className="p-3">Bağışçı</th><th className="p-3">Telefon</th><th className="p-3">Gelen</th><th className="p-3">Giden</th><th className="p-3">Ödeme</th><th className="p-3">Adet</th><th className="p-3 text-right">Tutar</th><th className="p-3">Durum</th></tr></thead><tbody>{rows.map((r)=><tr key={r.id} className="border-t"><td className="p-3">{r.receiptNo}</td><td className="p-3 font-semibold">{r.donorName}</td><td className="p-3">{r.phone}</td><td className="p-3">{r.origin}</td><td className="p-3">{r.destination}</td><td className="p-3">{r.payment}</td><td className="p-3">{r.quantity}</td><td className="p-3 text-right font-bold">{formatCurrency(r.amount)}</td><td className="p-3">{r.sent?"Gönderildi":"Bekliyor"}</td></tr>)}</tbody></table></div></div></div>}
