"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, Clock3, Globe2, LoaderCircle, RefreshCcw, Search, X } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { formatCurrency } from "@/lib/utils";

type Status = "PENDING" | "APPROVED" | "REJECTED";
type OnlineDonation = { id: string; externalReference: string; firstName: string; lastName: string; phone: string; email: string; originCity: string; originDistrict: string; campaign: string; amount: number; status: Status; createdAt: string };
type Summary = { pending: number; approved: number; rejected: number; approvedTotal: number };

export function OnlineDonations() {
  const [items, setItems] = useState<OnlineDonation[]>([]), [summary, setSummary] = useState<Summary>({ pending: 0, approved: 0, rejected: 0, approvedTotal: 0 });
  const [status, setStatus] = useState<Status>("PENDING"), [query, setQuery] = useState(""), [loading, setLoading] = useState(true), [processing, setProcessing] = useState(""), [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/online-donations", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setItems(data.donations ?? []); setSummary(data.summary ?? {}); } catch (reason) { setError(reason instanceof Error ? reason.message : "Online bağışlar yüklenemedi."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => { const text = query.trim().toLocaleLowerCase("tr-TR"); return items.filter((item) => item.status === status && (!text || `${item.firstName} ${item.lastName} ${item.phone} ${item.email} ${item.campaign} ${item.externalReference}`.toLocaleLowerCase("tr-TR").includes(text))); }, [items, query, status]);
  async function review(item: OnlineDonation, action: "APPROVE" | "REJECT") { if (!window.confirm(action === "APPROVE" ? `${item.firstName} ${item.lastName} bağışı onaylanıp bağışçılara eklensin mi?` : "Bu online bağış reddedilsin mi?")) return; setProcessing(item.id); setError(""); try { const response = await fetch(`/api/online-donations/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "İşlem tamamlanamadı."); } finally { setProcessing(""); } }
  const tabs: Array<{ value: Status; label: string; count: number }> = [{ value: "PENDING", label: "Onay Bekleyen", count: summary.pending }, { value: "APPROVED", label: "Onaylanan", count: summary.approved }, { value: "REJECTED", label: "Reddedilen", count: summary.rejected }];
  return <div className="mx-auto max-w-[1480px] space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-sky-700">Web sitesi entegrasyonu</p><h2 className="mt-1 text-xl font-bold text-[#0b2b3c]">Online Bağış Onay Listesi</h2><p className="mt-1 text-sm text-slate-500">Onaylanan kayıtlar bağışçı ve bağış tablolarına otomatik aktarılır.</p></div><Button variant="outline" onClick={() => void load()}><RefreshCcw className="size-4" /> Yenile</Button></div>
    <div className="grid gap-4 sm:grid-cols-3"><Metric icon={Clock3} label="Onay bekleyen" value={summary.pending.toString()} tone="amber" /><Metric icon={Check} label="Onaylanan" value={summary.approved.toString()} tone="emerald" /><Metric icon={Globe2} label="Onaylanan toplam" value={formatCurrency(summary.approvedTotal)} tone="sky" /></div>
    {error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <Card className="overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div className="flex flex-wrap gap-2">{tabs.map((tab) => <button key={tab.value} onClick={() => setStatus(tab.value)} className={`rounded-xl px-3 py-2 text-xs font-semibold ${status === tab.value ? "bg-[#0b2b3c] text-white" : "bg-slate-100 text-slate-600"}`}>{tab.label} <span className="ml-1 opacity-70">{tab.count}</span></button>)}</div><div className="relative w-full max-w-xs"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" placeholder="Bağışçı, telefon veya referans ara" /></div></div>
      {loading ? <div className="flex justify-center gap-2 p-14 text-sm text-slate-500"><LoaderCircle className="size-5 animate-spin" /> Kayıtlar yükleniyor</div> : <div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-xs"><thead className="bg-[#02b3aa] text-white"><tr>{["İşlem", "Tarih", "Referans", "Bağışçı", "Telefon", "E-posta", "İl / İlçe", "Kampanya", "Tutar", "Durum"].map((title) => <th key={title} className="px-4 py-3">{title}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item) => <tr key={item.id} className="hover:bg-emerald-50/40"><td className="px-4 py-3">{item.status === "PENDING" ? <div className="flex gap-2"><button disabled={processing === item.id} onClick={() => void review(item, "APPROVE")} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 font-semibold text-white"><Check className="size-3.5" /> Onayla</button><button disabled={processing === item.id} onClick={() => void review(item, "REJECT")} className="rounded-lg border border-red-200 p-2 text-red-600"><X className="size-3.5" /></button></div> : "—"}</td><td className="whitespace-nowrap px-4 py-3">{new Date(item.createdAt).toLocaleString("tr-TR")}</td><td className="px-4 py-3 font-medium">{item.externalReference}</td><td className="px-4 py-3 font-semibold text-slate-800">{item.firstName} {item.lastName}</td><td className="px-4 py-3">{item.phone}</td><td className="px-4 py-3">{item.email}</td><td className="px-4 py-3">{item.originCity} / {item.originDistrict}</td><td className="max-w-72 px-4 py-3">{item.campaign}</td><td className="px-4 py-3 font-bold text-emerald-700">{formatCurrency(item.amount)}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${item.status === "APPROVED" ? "bg-emerald-50 text-emerald-700" : item.status === "REJECTED" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{item.status === "APPROVED" ? "Onaylandı" : item.status === "REJECTED" ? "Reddedildi" : "Onay bekliyor"}</span></td></tr>)}{!filtered.length && <tr><td colSpan={10} className="p-14 text-center text-sm text-slate-500">Bu durumda online bağış kaydı bulunmuyor.</td></tr>}</tbody></table></div>}
    </Card></div>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof Globe2; label: string; value: string; tone: "amber" | "emerald" | "sky" }) { const classes = { amber: "bg-amber-50 text-amber-700", emerald: "bg-emerald-50 text-emerald-700", sky: "bg-sky-50 text-sky-700" }; return <Card className="flex items-center gap-4 p-5"><span className={`grid size-11 place-items-center rounded-xl ${classes[tone]}`}><Icon className="size-5" /></span><div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-[#0b2b3c]">{value}</p></div></Card>; }
